import { getFirebaseAccessToken } from "./firebase_management_client";
import { IS_TEST_BUILD } from "@/ipc/utils/test_utils";

export async function getFirebaseProjectInfo({
    projectId,
}: {
    projectId: string;
}) {
    if (IS_TEST_BUILD) {
        return `# Firebase Project Info\n\n## Project ID\n${projectId}\n\n## Collections\n["users", "settings"]`;
    }

    const token = await getFirebaseAccessToken();

    // List Collection IDs for Firestore (default database)
    const firestoreResponse = await fetch(
        `https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents:listCollectionIds`,
        {
            method: "POST",
            headers: {
                Authorization: `Bearer ${token}`,
                "Content-Type": "application/json",
            },
        }
    );

    let collections = [];
    if (firestoreResponse.ok) {
        const data = await firestoreResponse.json();
        collections = data.collectionIds || [];
    }

    let result = `# Firebase Project Info\n\n## Project ID\n${projectId}\n`;

    if (collections.length > 0) {
        result += `\n## Firestore Collections (root)\n${JSON.stringify(collections)}\n`;
    } else {
        result += `\nNo Firestore root collections found or Firestore is not enabled.\n`;
    }

    return result;
}

export async function getFirebaseConfigCode({
    appId,
    projectId,
    config
}: {
    appId: number;
    projectId: string;
    config: any;
}) {
    return `
// This file is automatically generated. Do not edit it directly.
import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getAuth } from "firebase/auth";
import { getStorage } from "firebase/storage";

const firebaseConfig = ${JSON.stringify(config, null, 2)};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Export services
export const db = getFirestore(app);
export const auth = getAuth(app);
export const storage = getStorage(app);
export default app;
`;
}
