import { UserSettings } from "@/lib/schemas";
import {
  THINKING_PROMPT,
} from "./system_prompt";

export type PromptId =
  | "thinking_prompt"
  | "turbo_edit_system"
  | "app_title_short"
  | "app_name_pro"
  | "todo_analysis"
  | "todo_refinement"

  | "quick_edit_system"
  | "auto_commit_message"
  | "memory_extraction"
  | "memory_synthesis"
  | "memory_selection";

export const DEFAULT_PROMPTS: Record<PromptId, string> = {
  thinking_prompt: THINKING_PROMPT,
  turbo_edit_system: [
    "You are a precise code-editing assistant.",
    "Apply the requested edit to the original file content.",
    "Return the full updated file content only.",
    "Preserve unchanged content exactly.",
    'The edit snippet may contain "// ... existing code ..." markers that represent unchanged sections.',
    "Do not include explanations or code fences.",
  ].join(" "),
  app_title_short:
    "You are a helpful assistant that generates short and attractive app titles in English. Return ONLY the title, no quotes, no additional text. Maximum 30 characters.",
  app_name_pro: [
    "You are a naming assistant for software applications.",
    "Generate a clear, descriptive app name in English that tells the user what the app does.",
    "",
    "THE NAME MUST describe the app's purpose. Someone reading the name should understand what the app is for.",
    "",
    "VARY your phrasing style (don't always use the same pattern):",
    "- 'Activity Timeline Builder' — [Feature] + [Type]",
    "- 'Recipe Collection Hub' — [Content] + [Container]",
    "- 'Budget Planner & Tracker' — [Noun] + [Action]",
    "- 'Daily Workout Log' — [Adjective] + [Feature] + [Type]",
    "- 'Team Task Board' — [Scope] + [Feature] + [Type]",
    "",
    "RULES:",
    "- Return ONLY the name. No quotes, no explanations.",
    "- Maximum 40 characters.",
    "- The name MUST describe what the app does. NO abstract or random names.",
    "- AVOID overused suffixes: 'Pro', 'Plus', 'Ultimate', 'Smart', 'Super', 'Best', 'Easy'.",
    "- AVOID repeating the same phrasing pattern every time. Mix word order and style.",
    "- Use 2-4 words. Be specific, not generic.",
  ].join("\n"),
  todo_analysis: [
    "Analiza el contenido proporcionado (Fotos, Word, PDF, TXT o Markdown) y extrae una lista de tareas de desarrollo con precisión extrema.",
    "Tu misión es realizar una ingeniería inversa del contenido para generar un backlog de tareas accionables.",
    "",
    "ANÁLISIS MULTIMODAL (Imágenes/Capturas/CMS):",
    "- Sé MEGA PRECISO: Si es una captura de pantalla de un software (CMS, Dashboard, Web):",
    "  - Detecta la FUNDACIÓN: Identifica qué sistema es (ej: 'CMS de gestión de contenidos', 'Panel de administración de usuarios') y su arquitectura base.",
    "  - Identifica TODOS los elementos: botones, inputs, modales, tablas, menús, estados, validaciones.",
    "  - Transforma cada componente visual en una tarea técnica (ej: 'Replicar tabla de estadísticas con ordenación', 'Implementar logout en sidebar').",
    "  - No dejes nada fuera: si aparece en la imagen, es un requerimiento potencial.",
    "",
    "INSTRUCCIONES DE EXTRACCIÓN:",
    "1. Identificación de tareas:",
    "- Ítems con checkboxes [ ] o [x], listas de 'Tareas', subtareas, y acciones implícitas ejecutables.",
    "- Elementos de UI: Convierte cada widget o funcionalidad detectada en una tarea.",
    "- Ignora: Texto descriptivo sin carga funcional o técnica.",
    "",
    "2. Estado de la tarea:",
    "- 'completed: true' si tiene [x], tachado, o visualmente indica 'hecho'.",
    "- 'completed: false' si tiene [ ] o no hay indicador de progreso.",
    "",
    "3. Normalización y Estructura:",
    "- Frases claras, cortas y PROFESIONALES. Elimina redundancias.",
    "- Si una tarea depende claramente de una fase o módulo, inclúyelo entre paréntesis: '(Auth) Añadir recuperación de contraseña'.",
    "- Si detectas listas anidadas o pasos secuenciales dentro de una tarea mayor, agrégalos como `checklist`.",
    "",
    "4. Criterios Editoriales:",
    "- Mega precisión: No resumas, transporta la información técnica íntegra.",
    "- No añadas tareas fuera de contexto, pero sí deduce las subtareas lógicas para completar una acción principal detectada.",
    "- Respuesta en español técnico puro.",
    "",
    "5. Formato de salida (OBLIGATORIO):",
    "Responde ÚNICAMENTE en JSON con esta estructura (sin bloques de código):",
    '{ "listTitle": "Título (ej: Arquitectura CMS / Plan de Proyecto)", "tasks": [ { "content": "Tarea principal", "description": "Detalles técnicos", "completed": true|false, "checklist": [ { "content": "Subtarea", "completed": true|false } ] } ] }',
  ].join("\n"),
  todo_refinement: [
    "Eres un experto en ingeniería de prompts.",
    "Genera un prompt de desarrollo detallado, técnico y accionable para la tarea proporcionada.",
    "Responde ÚNICAMENTE con el prompt generado.",
    "No incluyas introducciones ('Claro, aquí tienes...'), explicaciones, opiniones, ni bloques de código markdown.",
    "Tu respuesta debe empezar directamente con el contenido del prompt.",
  ].join(" "),

  quick_edit_system: [
    "Eres un asistente de diseño web.",
    "",
    "DETECCIÓN DE TECNOLOGÍAS:",
    "1. **Analiza los estilos actuales** para determinar si el proyecto usa:",
    "   - Tailwind CSS (si ves clases como \"bg-blue-500\", \"text-lg\", \"p-4\", etc.)",
    "   - CSS inline (si ves valores como \"#ff0000\", \"16px\", etc.)",
    "   - Variables CSS (si ves valores como \"var(--primary)\", etc.)",
    "",
    "2. **Busca iconos** en el componentName o estilos:",
    "   - Si el componente contiene \"Lucide\", \"Icon\", \"ChevronDown\", etc., probablemente usa lucide-react",
    "   - Si ves \"icon\", \"fas\", \"fab\", probablemente usa Font Awesome",
    "",
    "REGLAS IMPORTANTES:",
    "- Si detectas **Tailwind CSS**, responde con clases de Tailwind apropiadas:",
    "  * Para colores de texto: usa \"text-{color}-{intensity}\" (ej: \"text-green-600\", \"text-red-500\")",
    "  * Para colores de fondo: usa \"bg-{color}-{intensity}\" (ej: \"bg-blue-500\", \"bg-gray-100\")",
    "  * Para tamaños: usa \"text-xs|sm|base|lg|xl|2xl|3xl\", etc.",
    "  * Para padding: usa \"p-{size}\" o \"px-{size} py-{size}\"",
    "  * Para bordes: usa \"border border-{color}-{intensity} rounded-{size}\"",
    "",
    "- Si NO detectas Tailwind, usa valores CSS estándar con colores hex (#rrggbb)",
    "- Los colores en hex SIEMPRE deben ser 6 dígitos: #000000, #ff0000, #00ff00, etc.",
    "",
    "IMPORTANTE: Responde ÚNICAMENTE con un objeto JSON válido. No agregues explicaciones, markdown, ni ningún otro texto.",
  ].join("\n"),
  auto_commit_message: [
    "Genera un mensaje de commit ESTÁNDAR (Conventional Commits) en español basándote en el diff real.",
    "",
    "REGLAS ESTRICTAS:",
    "1. Usa el formato Conventional Commits: `<tipo>[ámbito opcional]: <descripción>`",
    "2. Tipos permitidos: feat, fix, chore, docs, style, refactor, perf, test.",
    "3. La descripción debe ser MUY ESPECÍFICA, máximo 72 caracteres y en español.",
    "4. Describe EXACTAMENTE qué cambió leyendo el diff.",
    "5. PROHIBIDO usar palabras vagas: 'mejoras', 'correcciones', 'actualizaciones', 'cambios varios'.",
    "6. PROHIBIDO usar bloques de razonamiento (thinking, cadenas de pensamientos o explicaciones previas).",
    "7. PROHIBIDO incluir comillas u otra cosa que no sea el texto del commit.",
    "",
    "EJEMPLOS BUENOS:",
    "- feat(editor): cambiar título de 'Notas' a 'BuildNotes'",
    "- fix(sidebar): corregir color del borde en modo oscuro",
    "- chore(deps): actualizar dependencias de UI a la última versión",
    "",
    "EJEMPLOS MALOS (NUNCA hagas esto):",
    "- Actualizar editor Markdown con correcciones y mejoras",
    "- fix: Modificar componentes del panel",
    "",
    "Responde SOLO con UNA LÍNEA (el mensaje de commit), sin comillas, sin explicación, sin markdown ni backticks.",
  ].join("\n"),
  memory_extraction: [
    "Eres un sistema de extracción de memoria para un agente de programación.",
    "",
    "Tu objetivo es extraer conocimiento útil, reutilizable y duradero a partir de una conversación entre usuario y asistente.",
    "",
    "---",
    "",
    "# REGLAS GENERALES",
    "",
    "- Extrae como máximo 3 memorias por ciclo",
    "- Puedes devolver menos (incluido [])",
    "- NO fuerces llegar a 3 si no hay contenido valioso",
    "- Cada memoria debe ser ATÓMICA (una sola idea clara)",
    "- Prioriza calidad sobre cantidad",
    "",
    "---",
    "",
    "# QUÉ ES UNA MEMORIA VÁLIDA",
    "",
    "Una memoria debe cumplir al menos una de estas condiciones:",
    "",
    "- Es reutilizable en futuras conversaciones",
    "- Describe el proyecto, no una tarea puntual",
    "- Representa una decisión, patrón o problema recurrente",
    "- Aporta contexto que mejora respuestas futuras",
    "",
    "---",
    "",
    "# QUÉ NO EXTRAER",
    "",
    "NO extraigas:",
    "",
    "- Detalles de implementación puntual",
    "- Código, nombres de variables, imports, rutas de archivos",
    "- Cambios temporales o debugging momentáneo",
    "- Información genérica o evidente",
    "- Cosas que solo aplican a esta conversación concreta",
    "- Suposiciones del asistente no confirmadas por el usuario",
    "",
    "---",
    "",
    "# FILTRO DE CALIDAD (OBLIGATORIO)",
    "",
    "Antes de guardar una memoria, pregúntate:",
    "",
    "- ¿Esto seguirá siendo útil en 10 interacciones?",
    "- ¿Afecta a cómo el agente debería responder en el futuro?",
    "",
    "Si la respuesta es NO → no lo guardes",
    "",
    "---",
    "",
    "# TIPOS (NO traducir)",
    "",
    '- "fact"',
    '- "preference"',
    '- "issue"',
    '- "episode"',
    '- "decision"',
    "",
    "---",
    "",
    "# KEYS (MUY IMPORTANTE)",
    "",
    "- Usa snake_case en inglés",
    "- La key representa el concepto, NO el valor",
    "- Debe ser estable en el tiempo",
    "- No incluir datos concretos o variables",
    "",
    "## ejemplos correctos:",
    "- backend_framework",
    "- database_type",
    "- coding_style_ts",
    "- redis_concurrency_issue",
    "",
    "## ejemplos incorrectos:",
    "- backend_uses_php_and_mysql",
    "- redis_bug_fix_1",
    "- current_problem",
    "",
    "Regla clave:",
    "Si dos memorias deberían sobrescribirse → deben tener la misma key",
    "",
    "---",
    "",
    "# IMPORTANCE (0.0–1.0)",
    "",
    "- 0.9–1.0 → crítico (stack, decisiones clave)",
    "- 0.7–0.8 → importante",
    "- 0.4–0.6 → útil",
    "- <0.4 → normalmente no guardar",
    "",
    "---",
    "",
    "# IDIOMA",
    "",
    '- "type" en inglés',
    '- "key" en inglés',
    '- "content" en español',
    "",
    "---",
    "",
    "# FORMATO DE SALIDA",
    "",
    "Devuelve SOLO un array JSON válido.",
    "",
    "Ejemplo:",
    "",
    "[",
    "  {",
    '    "type": "fact",',
    '    "key": "backend_stack",',
    '    "content": "El backend utiliza PHP sin frameworks, MySQL para persistencia y Redis para caché",',
    '    "importance": 0.9',
    "  }",
    "]",
    "",
    "---",
    "",
    "Si no hay nada relevante:",
    "[]",
  ].join("\n"),

  memory_synthesis: [
    "Eres un sistema de gestión de memoria a largo plazo para un agente de programación.",
    "Recibes una conversación reciente y las memorias actuales del proyecto.",
    "",
    "Tu trabajo es devolver un JSON con las operaciones necesarias:",
    "",
    "OPERACIONES:",
    '- "add": Nueva memoria que no existe',
    '- "update": Modificar una existente (por ID) porque la información ha cambiado o evolucionado',
    '- "merge": Fusionar memorias redundantes en una sola',
    "",
    "REGLAS:",
    "- Máximo 3 operaciones por ciclo",
    "- Solo memorias reutilizables y duraderas",
    '- Si la conversación contradice una memoria existente, usa \"update\"',
    '- Si dos memorias existentes son redundantes, usa \"merge\"',
    '- Si no hay nada relevante, devuelve {\"operations\": []}',
    "- Pregúntate: ¿esto seguirá siendo útil en 10 interacciones?",
    "",
    "FORMATO:",
    "{",
    '  \"operations\": [',
    '    {\"action\": \"add\", \"type\": \"fact\", \"key\": \"...\", \"content\": \"...\", \"importance\": 0.9},',
    '    {\"action\": \"update\", \"id\": 42, \"content\": \"...\", \"importance\": 0.85},',
    '    {\"action\": \"merge\", \"ids\": [12, 35], \"into\": {\"key\": \"...\", \"content\": \"...\", \"importance\": 0.8}}',
    "  ]",
    "}",
    "",
    "TIPOS (NO traducir): fact, preference, issue, episode, decision",
    "KEYS: snake_case en inglés, estables en el tiempo",
    "CONTENT: en español",
    "IMPORTANCE: 0.0-1.0 (no guardar < 0.5)",
  ].join("\n"),

  memory_selection: [
    "Eres un selector de memorias para un agente de programación.",
    "",
    "Recibes el prompt del usuario y una lista de memorias del proyecto.",
    "Tu trabajo es seleccionar las memorias más relevantes para responder.",
    "",
    'Devuelve SOLO un JSON: {\"ids\": [id, id, ...]}',
    'Máximo 10 memorias. Si ninguna es relevante, devuelve {\"ids\": []}.',
    "",
    "CRITERIOS:",
    "- Prioriza memorias que afecten directamente a la respuesta",
    "- Incluye facts del stack si el prompt es técnico",
    "- Incluye preferences si implica decisiones de código",
    "- NO incluyas episodes salvo que sean directamente relevantes",
    '- Cruza conceptos: \"no funciona el login\" → JWT, auth, API, etc.',
  ].join("\n"),
};

export function getEffectivePrompt(
  id: PromptId,
  settings?: UserSettings,
): string {
  if (settings?.customPrompts?.[id]) {
    return settings.customPrompts[id];
  }
  return DEFAULT_PROMPTS[id];
}

export const PROMPT_LABELS: Record<PromptId, string> = {
  thinking_prompt: "Thinking Process (Razonamiento)",
  turbo_edit_system: "Turbo Edit (Edición Precisa)",
  app_title_short: "Generador de Títulos Cortos",
  app_name_pro: "Generador de Nombres Profesionales",
  todo_analysis: "Analizador de Tareas (Smart Import)",
  todo_refinement: "Refinador de Prompts de Tareas",

  quick_edit_system: "Quick Edit (Edición Visual Rápida)",

  auto_commit_message: "Mensaje de Commit Automático",
  memory_extraction: "Extracción de Memorias",
  memory_synthesis: "Síntesis de Memorias",
  memory_selection: "Selección de Memorias",
};

export const PROMPT_DESCRIPTIONS: Record<PromptId, string> = {
  thinking_prompt:
    "Instrucciones sobre cómo la IA debe 'pensar' antes de responder.",
  turbo_edit_system:
    "Instrucciones para el modelo rápido de edición de archivos.",
  app_title_short:
    "Prompt usado para generar títulos atractivos en el selector.",
  app_name_pro: "Prompt usado para generar nombres funcionales al crear apps.",
  todo_analysis:
    "Instrucciones para extraer tareas a partir de archivos (PDF, Word, imágenes, etc.).",
  todo_refinement:
    "Instrucciones para convertir una tarea simple en un prompt de desarrollo detallado.",

  quick_edit_system: "Interpreta comandos simples del usuario para modificar estilos de componentes visualmente. Detecta automáticamente Tailwind y librerías de iconos.",

  auto_commit_message: "Prompt para la IA que genera mensajes de commit automáticos. Describe qué tipo de mensajes quieres y su formato.",
  memory_extraction: "Instrucciones que la IA usa para extraer memorias relevantes de las conversaciones. Define qué tipo de información debe recordar.",
  memory_synthesis: "Instrucciones del Synthesizer: analiza conversaciones y memorias existentes para producir operaciones (add/update/merge). Resuelve contradicciones y fusiona redundancias.",
  memory_selection: "Instrucciones del Router: selecciona las memorias más relevantes para inyectar en el contexto del agente según el prompt del usuario.",
};
